export const SET_CURRENT_ROUTE = "SET_CURRENT_ROUTE";

export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const SET_SELECTED_TAGS = "SET_SELECTED_TAGS";
export const ADD_SELECTED_TAG = "ADD_SELECTED_TAG";
export const REMOVE_SELECTED_TAG = "REMOVE_SELECTED_TAG";
export const RESET_SELECTED_TAGS = "RESET_SELECTED_TAGS";
export const SET_DEFAULT_OPTIONS = "SET_DEFAULT_OPTIONS";
export const SET_FILTERED_OPTIONS = "SET_FILTERED_OPTIONS";
export const RESET_FILTERED_OPTIONS = "RESET_FILTERED_OPTIONS";
export const SET_RECIPES = "SET_RECIPES";
export const SET_DISPLAYED_RECIPES = "SET_DISPLAYED_RECIPES";
export const RESET_DISPLAYED_RECIPES = "RESET_DISPLAYED_RECIPES";
