export const SET_CURRENT_ROUTE = "SET_CURRENT_ROUTE";

export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const SET_SELECTED_TAGS = "SET_SELECTED_TAGS";
export const RESET_SELECTED_TAGS = "RESET_SELECTED_TAGS";
export const SET_DEFAULT_OPTIONS = "SET_DEFAULT_OPTIONS";
export const SET_FILTERED_OPTIONS = "SET_FILTERED_OPTIONS";
